version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: gru_app_postgres
    environment:
      POSTGRES_USER: gru_user
      POSTGRES_PASSWORD: gru_password
      POSTGRES_DB: gru_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
